tasks:
  - name: Ensure we have a directory for nginx configs and SSL certs
    file:
      path: "{{ gb_root }}/volumes/nginx/ssl"
      state: directory

  - name: Copy over base nginx config
    copy:
      src: base.conf
      dest: "{{ gb_root }}/volumes/nginx/nginx.conf"

  - name: Copy over proxy config files for the services
    copy:
      src: services 
      dest: "{{ gb_root }}/volumes/nginx"

compose:
  nginx:
    image: nginx
    volumes:
      - ./volumes/nginx/ssl:/etc/nginx/ssl
      - ./volumes/nginx/services:/etc/nginx/conf.d/services
      - ./volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
    restart: always
